### ISSUE TITLE
Fix broken old migrations

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#77]
There are duplicates and things which make the installation of the system from scratch a challenge.

**Comment by sdrogers** [comment]
Joe: it would be great if you could look into this....

**Comment by joewandy** [comment]
Shall we just do Scenario 2 in this link https://simpleisbetterthancomplex.com/tutorial/2016/07/26/how-to-reset-migrations.html?

**Comment by sdrogers** [comment]
Will that fix the problem though? The issue seemed to be with creating a clean system using postgres?

**Comment by RonanDaly** [comment]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/ronan/work/ms2ldaviz/ms2ldaviz/ms2ldaviz/urls.py", line 23, in <module>
    url(r'^decomposition/',include('decomposition.urls')),
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/ronan/work/ms2ldaviz/ms2ldaviz/decomposition/urls.py", line 3, in <module>
    from decomposition import views
  File "/Users/ronan/work/ms2ldaviz/ms2ldaviz/decomposition/views.py", line 9, in <module>
    from decomposition.forms import DecompVizForm,NewDecompositionForm,BatchDecompositionForm,SpectrumForm
  File "/Users/ronan/work/ms2ldaviz/ms2ldaviz/decomposition/forms.py", line 23, in <module>
    class SpectrumForm(forms.Form):
  File "/Users/ronan/work/ms2ldaviz/ms2ldaviz/decomposition/forms.py", line 26, in SpectrumForm
    motifset = forms.ChoiceField(required = True,choices = [(m.id,m.name) for m in MotifSet.objects.all()])
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/ronan/work/ms2ldaviz/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "decomposition_motifset" does not exist
LINE 1: ...e", "decomposition_motifset"."featureset_id" FROM "decomposi...
```

**Comment by RonanDaly** [comment]
This is the crucial problem
```
    motifset = forms.ChoiceField(required = True,choices = [(m.id,m.name) for m in MotifSet.objects.all()])
```
The model definition is looking at the database

**Comment by joewandy** [comment]
That looks like a form instead?

**Comment by RonanDaly** [comment]
Yes, the form is being attempted to be created on an empty database, so is failing; the definition is probably not correct.

**Comment by sdrogers** [comment]
Should be easy to fix -- stuff like that ought to be in the __init__ method for the form, so it's only called when the form object is created...I don't have time to fix now: maybe @joewandy could do the necessary quick fix?

**Comment by joewandy** [comment]
Fixed!

**Comment by RonanDaly** [comment]
Done. Though it might be a better solution to remove those migrations totally.
